bindPort = 7000

vhostHTTPPort = 80
webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "xuegodalexadmin123"
auth.method = "token"
auth.token = "xuegodalex123"
