bindPort = 7000

vhostHTTPPort = 80 # 虚拟主机的 HTTP 端口。
webServer.addr = "0.0.0.0" # 仪表盘的绑定地址。
webServer.port = 7500 # 仪表板的监听端口。
webServer.user = "admin" # 仪表板的用户名。
webServer.password = "xuegodalexadmin123" # 仪表板的密码。
auth.method = "token" # 认证方法。
auth.token = "xuegodalex123" # 认证令牌。